name: budgetease
description: "Une application de gestion de budget personnel"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  provider: ^6.1.2
  fl_chart: ^0.66.2
  intl: ^0.19.0
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
